"""Build a generated documentation summary for the AI Engineer Pack.

Usage examples:
    python scripts/build_docs.py
    python scripts/build_docs.py --check
    python scripts/build_docs.py --root G:/AI-Engineer-Pack

Exit codes:
    0: summary generated or already current
    1: generation failed or --check detected stale output
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

LOGGER = logging.getLogger("build_docs")


def repository_root(start: Path | None = None) -> Path:
    """Return the repository root inferred from this script location."""

    if start is None:
        start = Path(__file__).resolve()
    return start.parents[1]


def count_dirs(path: Path) -> int:
    """Count immediate child directories."""

    return len([item for item in path.iterdir() if item.is_dir()]) if path.exists() else 0


def count_files(path: Path, pattern: str) -> int:
    """Count files matching a pattern below a path."""

    return len(list(path.rglob(pattern))) if path.exists() else 0


def folder_summary(root: Path) -> list[tuple[str, str, int, int]]:
    """Return summary data for primary repository folders."""

    folders = ["system", "routers", "frameworks", "commands", "chatgpt", "codex", "agents", "mcp", "skills", "templates", "checklists", "examples", "docs", "scripts", ".github"]
    rows: list[tuple[str, str, int, int]] = []
    for name in folders:
        path = root / name
        purpose = summary_from_readme(path / "README.md") if path.exists() else "Folder is missing."
        rows.append((name, purpose, count_dirs(path), count_files(path, "*.md")))
    return rows


def summary_from_readme(readme: Path) -> str:
    """Extract a short purpose summary from a README."""

    if not readme.exists():
        return "No README found."
    lines = [line.strip() for line in readme.read_text(encoding="utf-8").splitlines()]
    for index, line in enumerate(lines):
        if line == "## Purpose":
            for candidate in lines[index + 1 :]:
                if candidate and not candidate.startswith("#"):
                    return candidate.replace("|", "\\|")
    return "Purpose summary is not available."


def build_summary(root: Path, generated_at: datetime | None = None) -> str:
    """Create the documentation summary Markdown."""

    generated_at = generated_at or datetime.now(timezone.utc)
    agent_count = count_dirs(root / "agents")
    mcp_count = count_dirs(root / "mcp")
    skill_categories = count_dirs(root / "skills")
    skill_files = count_files(root / "skills", "SKILL.md")
    framework_count = count_dirs(root / "frameworks")
    command_count = count_dirs(root / "commands")
    template_count = count_dirs(root / "templates")
    checklist_count = count_dirs(root / "checklists")
    markdown_count = count_files(root, "*.md")
    python_count = count_files(root / "scripts", "*.py")

    rows = ["| Folder | Purpose | Subfolders | Markdown files |", "|---|---|---:|---:|"]
    for folder, purpose, subfolders, markdown_files in folder_summary(root):
        rows.append(f"| `{folder}/` | {purpose} | {subfolders} | {markdown_files} |")

    return f"""# Documentation Summary

Generated by `python scripts/build_docs.py`.

Latest generated date: {generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}

## Repository overview
The AI Engineer Pack is a Markdown-first repository of systems guidance, routers, prompt frameworks, reusable commands, skills, templates, checklists, examples, and project documentation for ChatGPT, Codex, GitHub Copilot, OpenAI Agents, and future AI coding assistants.

## Module counts
- Agents: {agent_count}
- MCP modules: {mcp_count}
- Skill categories: {skill_categories}
- Skill definitions: {skill_files}
- Frameworks: {framework_count}
- Commands: {command_count}
- Templates: {template_count}
- Checklists: {checklist_count}
- Markdown files: {markdown_count}
- Python scripts: {python_count}

## Folder summary
{chr(10).join(rows)}

## Generated indexes
- [Agent Index](AGENT_INDEX.md)
- [MCP Index](MCP_INDEX.md)
- [Skill Index](SKILL_INDEX.md)
- [Framework Index](FRAMEWORK_INDEX.md)
- [Command Index](COMMAND_INDEX.md)
- [Template Index](TEMPLATE_INDEX.md)
- [Checklist Index](CHECKLIST_INDEX.md)
- [Example Index](EXAMPLE_INDEX.md)
- [System Index](SYSTEM_INDEX.md)
"""


def write_summary(root: Path, check: bool = False) -> bool:
    """Write docs/SUMMARY.md or check whether it is current enough.

    The generated date changes on every write, so --check verifies that the file exists
    and contains the required sections rather than byte-for-byte equality.
    """

    output_path = root / "docs" / "SUMMARY.md"
    if check:
        if not output_path.exists():
            LOGGER.error("Missing docs/SUMMARY.md")
            return False
        text = output_path.read_text(encoding="utf-8")
        required = ["## Repository overview", "## Folder summary", "## Module counts", "Latest generated date"]
        missing = [section for section in required if section not in text]
        for section in missing:
            LOGGER.error("docs/SUMMARY.md missing section: %s", section)
        return not missing
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(build_summary(root), encoding="utf-8")
    print(f"Wrote {output_path.relative_to(root).as_posix()}")
    return True


def build_parser() -> argparse.ArgumentParser:
    """Create the command-line parser."""

    parser = argparse.ArgumentParser(description="Generate docs/SUMMARY.md for the AI Engineer Pack.")
    parser.add_argument("--root", type=Path, default=repository_root(), help="Repository root.")
    parser.add_argument("--check", action="store_true", help="Check whether docs/SUMMARY.md exists and has required sections.")
    parser.add_argument("--verbose", action="store_true", help="Enable debug logging.")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Build documentation summary and return an exit code."""

    args = build_parser().parse_args(argv)
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO, format="%(levelname)s: %(message)s")
    try:
        return 0 if write_summary(args.root.resolve(), check=args.check) else 1
    except OSError as exc:
        LOGGER.error("Documentation summary generation failed: %s", exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())



