"""Generate Markdown index files for the AI Engineer Pack.

Usage examples:
    python scripts/generate_index.py
    python scripts/generate_index.py --check
    python scripts/generate_index.py --root G:/AI-Engineer-Pack

Exit codes:
    0: indexes generated or already current
    1: generation failed or --check detected stale output
"""

from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

LOGGER = logging.getLogger("generate_index")
GENERATED_NOTE = "Generated by `python scripts/generate_index.py`. Do not edit by hand."
SOURCE_BASE_URL = "https://github.com/HasainalFaruk/AI-Engineer-Pack/blob/main/"


@dataclass(frozen=True)
class IndexRow:
    """A row in a generated Markdown index."""

    name: str
    path: str
    summary: str


def repository_root(start: Path | None = None) -> Path:
    """Return the repository root inferred from this script location."""

    if start is None:
        start = Path(__file__).resolve()
    return start.parents[1]


def title_from_markdown(markdown_file: Path, fallback: str) -> str:
    """Extract the first H1 title from a Markdown file."""

    if markdown_file.exists():
        for raw_line in markdown_file.read_text(encoding="utf-8").splitlines():
            line = raw_line.lstrip("\ufeff")
            if line.startswith("# "):
                return line[2:].strip()
    return fallback.replace("-", " ").replace("_", " ").title()


def summary_from_markdown(markdown_file: Path) -> str:
    """Extract the first useful summary sentence from a Markdown file."""

    if not markdown_file.exists():
        return "Documentation is not available."
    lines = [line.strip() for line in markdown_file.read_text(encoding="utf-8").splitlines()]
    for index, line in enumerate(lines):
        if line == "## Purpose":
            for candidate in lines[index + 1 :]:
                if candidate and not candidate.startswith("#"):
                    return candidate.replace("|", "\\|")
    for line in lines:
        if line and not line.startswith("#") and not line.startswith("-") and not line.startswith("Generated by"):
            return line.replace("|", "\\|")
    return "No summary available."


def row_for_folder(root: Path, folder: Path) -> IndexRow:
    """Build an index row for a folder with a README."""

    readme = folder / "README.md"
    rel = readme.relative_to(root).as_posix() if readme.exists() else folder.relative_to(root).as_posix()
    return IndexRow(title_from_markdown(readme, folder.name), rel, summary_from_markdown(readme))


def row_for_file(root: Path, markdown_file: Path) -> IndexRow:
    """Build an index row for a Markdown file."""

    rel = markdown_file.relative_to(root).as_posix()
    return IndexRow(title_from_markdown(markdown_file, markdown_file.stem), rel, summary_from_markdown(markdown_file))


def skill_rows(root: Path) -> list[IndexRow]:
    """Collect skill category and technology rows."""

    rows: list[IndexRow] = []
    skills_dir = root / "skills"
    for category in sorted([path for path in skills_dir.iterdir() if path.is_dir()], key=lambda p: p.name):
        category_title = title_from_markdown(category / "README.md", category.name)
        rows.append(row_for_folder(root, category))
        for technology in sorted([path for path in category.iterdir() if path.is_dir()], key=lambda p: p.name):
            row = row_for_folder(root, technology)
            rows.append(IndexRow(f"{category_title} / {row.name}", row.path, row.summary))
    return rows


def simple_rows(root: Path, folder_name: str) -> list[IndexRow]:
    """Collect rows for simple one-level folders."""

    folder = root / folder_name
    if not folder.exists():
        return []
    return [row_for_folder(root, path) for path in sorted(folder.iterdir(), key=lambda p: p.name) if path.is_dir()]


def markdown_file_rows(root: Path, folder_name: str) -> list[IndexRow]:
    """Collect rows for Markdown files under a folder."""

    folder = root / folder_name
    if not folder.exists():
        return []
    return [row_for_file(root, path) for path in sorted(folder.glob("*.md"), key=lambda p: p.name)]


def source_link(path: str) -> str:
    """Return a stable GitHub source URL for a repository path."""

    return f"{SOURCE_BASE_URL}{path}"


def markdown_table(rows: Iterable[IndexRow]) -> str:
    """Render rows as a Markdown table."""

    output = ["| Name | Source | Summary |", "|---|---|---|"]
    for row in sorted(rows, key=lambda item: item.name.lower()):
        output.append(f"| {row.name} | [{row.path}]({source_link(row.path)}) | {row.summary} |")
    return "\n".join(output)


def document(title: str, rows: list[IndexRow]) -> str:
    """Create a full Markdown index document."""

    return f"# {title}\n\n{GENERATED_NOTE}\n\nTotal entries: {len(rows)}\n\n{markdown_table(rows)}\n"


def outputs(root: Path) -> dict[Path, str]:
    """Return generated index output paths and contents."""

    return {
        root / "docs" / "AGENT_INDEX.md": document("Agent Index", simple_rows(root, "agents")),
        root / "docs" / "MCP_INDEX.md": document("MCP Index", simple_rows(root, "mcp")),
        root / "docs" / "SKILL_INDEX.md": document("Skill Index", skill_rows(root)),
        root / "docs" / "FRAMEWORK_INDEX.md": document("Framework Index", simple_rows(root, "frameworks")),
        root / "docs" / "COMMAND_INDEX.md": document("Command Index", simple_rows(root, "commands")),
        root / "docs" / "TEMPLATE_INDEX.md": document("Template Index", simple_rows(root, "templates")),
        root / "docs" / "CHECKLIST_INDEX.md": document("Checklist Index", simple_rows(root, "checklists")),
        root / "docs" / "EXAMPLE_INDEX.md": document("Example Index", markdown_file_rows(root, "examples")),
        root / "docs" / "SYSTEM_INDEX.md": document("System Index", markdown_file_rows(root, "system")),
    }


def write_outputs(root: Path, check: bool = False) -> bool:
    """Write generated indexes. Return True when files are current or written."""

    root.joinpath("docs").mkdir(exist_ok=True)
    ok = True
    for path, content in outputs(root).items():
        if check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                LOGGER.error("Generated index is stale or missing: %s", path.relative_to(root).as_posix())
                ok = False
        else:
            path.write_text(content, encoding="utf-8")
            print(f"Wrote {path.relative_to(root).as_posix()}")
    return ok


def build_parser() -> argparse.ArgumentParser:
    """Create the command-line parser."""

    parser = argparse.ArgumentParser(description="Generate AI Engineer Pack index documentation.")
    parser.add_argument("--root", type=Path, default=repository_root(), help="Repository root.")
    parser.add_argument("--check", action="store_true", help="Check whether generated indexes are current without writing.")
    parser.add_argument("--verbose", action="store_true", help="Enable debug logging.")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Generate indexes and return an exit code."""

    args = build_parser().parse_args(argv)
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO, format="%(levelname)s: %(message)s")
    root = args.root.resolve()
    try:
        return 0 if write_outputs(root, check=args.check) else 1
    except OSError as exc:
        LOGGER.error("Index generation failed: %s", exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())

